<?php
namespace common\components;

class Controller extends \yii\web\Controller
{
    public function init()
    {
//        \Yii::$app->urlManager->baseUrl .= '\\' . \Yii::$app->request->get('app');
        parent::init(); // TODO: Change the autogenerated stub
    }
}