<?php

namespace common\components;


class Module extends \yii\base\Module
{
    private $_viewPath;

    public function init()
    {
        $this->controllerNamespace = 'app\modules\\'.$this->id.'\controllers\\' . \Yii::$app->request->get('app');
//        $this->layoutPath = $this->getBasePath();

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getViewPath()
    {
        if ($this->_viewPath === null) {
            $this->_viewPath = $this->getBasePath() . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR . \Yii::$app->request->get('app');
        }

        return $this->_viewPath;
    }
}